# Generated by Django 4.2.6 on 2023-10-19 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_client_problem_health'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='data_update',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='client',
            name='date_create',
            field=models.DateTimeField(),
        ),
    ]
