# Generated by Django 4.2.6 on 2023-10-24 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_client_date_create'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='date_create',
            field=models.DateField(),
        ),
    ]
